#通用配置
#服务注册中心配置
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://127.0.0.1:8761/eureka/}
  instance:
    hostname: ${spring.cloud.client.ipAddress}  
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}  
    prefer-ip-address: true  
    nonSecurePort: ${server.port}  
